# Numpy

## List vs Array

- liste Python, c'est comme une boite a outils. Chaque element est independant, donc les ranger prend du temps.
- Un array Numpy (ndarray), c'est un tournevis electrique. Operations se font ensemble,
d'un coup, en masse.

## Installation et vérification

In [1]:
# dans le terminal : pip install numpy
# dans une cellule notebook : !pip install numpy
# Pour un reinstall propre forcé : pip install --force-reinstall --no-cache-dir numpy
# python -m pip install numpy
import numpy as np

# verification
print(np.__version__)

2.4.3


## Creation d'arrays et attributs

In [2]:
l = [1,2,3,4,5,6,7,8,9]
a = np.array(l)

print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(9,)


In [3]:
l = [1,2,3,4,5.4,6,7,8,9]
a = np.array(l)
print(a)

[1.  2.  3.  4.  5.4 6.  7.  8.  9. ]


In [4]:
np.array([1.5,1,True,False, "azerty"])

array(['1.5', '1', 'True', 'False', 'azerty'], dtype='<U32')

In [5]:
liste = [1,2,3,4,5]
a = np.array([1,2,3,4,5])

#operation sur la liste
print([x*2 for x in liste])

# operation sur array
print(a * 2)

[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


## Difference de vitesse

In [6]:
import time
liste = list(range(10_000_000))
a = np.arange(10_000_000)

#liste
t0 = time.perf_counter()
resultat_liste = [x*2 for x in liste]
t1 = time.perf_counter()

#array
t2 = time.perf_counter()
resultat_array = a * 2
t3 = time.perf_counter()

print(f"Liste Python : {(t1 - t0)*1000:.2f} ms")
print(f"NumPy        : {(t3 - t2)*1000:.2f} ms")
print(f"Accélération : {(t1 - t0)/(t3 - t2):.1f}x")

Liste Python : 1402.37 ms
NumPy        : 34.29 ms
Accélération : 40.9x


## Les fonctions constructeurs

In [7]:
print(f"np.arange(10) = {np.arange(10)}")
print(f"np.arange(2, 10, 2) = {np.arange(2, 10, 2)}")

print(f"np.zeros(5) = {np.zeros(5)}")
print(f"np.ones(5) = {np.ones(5)}")
print(f"np.ones(5) = \n{np.ones((3,4))}")

# points egalement espacés
print(f"np.linspace(0, 100, 5) = {np.linspace(0, 100, 5)}")

#reshape
print(f"{np.arange(12).reshape(3, 4)}")

#
print(np.arange(12).reshape(1,12).shape)

np.arange(10) = [0 1 2 3 4 5 6 7 8 9]
np.arange(2, 10, 2) = [2 4 6 8]
np.zeros(5) = [0. 0. 0. 0. 0.]
np.ones(5) = [1. 1. 1. 1. 1.]
np.ones(5) = 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
np.linspace(0, 100, 5) = [  0.  25.  50.  75. 100.]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(1, 12)


## les attributs

In [8]:
a = np.arange(24).reshape(4,6)
print(a)
print(f"Forme : {a.shape}")
print(f"Nombre dimensions : {a.ndim}")
print(f"Type : {a.dtype}")
print(f"Taille : {a.size}")
print(f"Taille element : {a.itemsize}")
print(f"Memoire totale : {a.nbytes}")

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Forme : (4, 6)
Nombre dimensions : 2
Type : int64
Taille : 24
Taille element : 8
Memoire totale : 192


## Génération aléatoire

In [9]:
rng = np.random.default_rng(42)
print(rng.random(5))
print(rng.integers(0, 21, 10))
print(rng.normal(12, 3, 20))

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[11 20 15 15 15 16 10  2 17  9]
[14.63819392 14.33337581 12.19809209 15.38172362 13.40252803  9.42212261
 13.10625235  9.1233522  14.6353509  11.85022227 11.44541291  9.95721137
 15.66762402 11.53641155 10.71501653 10.94359935 13.59692756 13.09633219
 13.23819783 13.29246301]


## Exercice 1

In [10]:
# 1. Créer un array à partir de [5, 10, 15, 20, 25, 30]
a = np.array([5, 10, 15, 20, 25, 30])
print(f"Q1 : {a}")
# 2. Afficher sa forme, son nombre de dimensions, son type
print(f"Q2 : forme={a.shape}, nombre dimensions={a.ndim}, type={a.dtype}")
# 3. Créer un array de 0 à 20 (exclu) avec arange
print(f"Q3 : {np.arange(0,20)}")
# 4. Créer un vecteur de 10 zéros
print(f"Q4 : {np.zeros(10)}")
# 5. Créer une matrice de 1 de forme 3×4
print(f"Q5 : \n{np.ones((3,4))}")
# 6. Créer un vecteur de 7 points équidistants entre 0 et 1
print(f"Q6 : {np.linspace(0,1,7)}")
# 7. Créer un tableau 5×5 rempli de nombres aléatoires entiers entre 1 et 100 inclu
rng = np.random.default_rng()
print(rng.integers(1,101,(5,5)))

Q1 : [ 5 10 15 20 25 30]
Q2 : forme=(6,), nombre dimensions=1, type=int64
Q3 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Q4 : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Q5 : 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Q6 : [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]
[[43 46 63 29  1]
 [94 64 17 39 87]
 [83 53 39 18 48]
 [ 3 75 36 64 76]
 [19  8 64 78 13]]


## Indexation et Slicing

### indexation de base

In [11]:
data = np.array([10,20,30,40,50,60,70,80])
print(data)
#indexation
print(data[0], data[-1], data[3])

#slicing
print(data[1:4])
print(data[:5])
print(data[-3:])
print(data[::2])

[10 20 30 40 50 60 70 80]
10 80 40
[20 30 40]
[10 20 30 40 50]
[60 70 80]
[10 30 50 70]


### Indexation 2d

In [12]:
mat = np.arange(16).reshape(4,4)
print(mat)

print(mat[1, 2])
print(mat[0, :])
print(mat[:, 0])
print(mat[-2:,:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
6
[0 1 2 3]
[ 0  4  8 12]
[[ 8  9 10]
 [12 13 14]]


### Indexation booleenne

In [13]:
data = np.array([10,20,30,40,50,60,70,80])

print(data[data <= 50])
print(data[(data <= 50) & (data > 20)])
print(data[(data < 30) | (data > 60)])

[10 20 30 40 50]
[30 40 50]
[10 20 70 80]


In [14]:
# print(data[data < 30 | data > 60]) ERREUR
# print(data[30 < data < 60]) ERREUR
# Il faut separer les conditions et il faut mettre les parentheses pour chaque condition

## Exercice 2

In [15]:
rng = np.random.default_rng(42)
notes = rng.integers(0, 21, 30)  # 30 notes entre 0 et 20
print("Notes :", notes)

# 1. Afficher la note de l'étudiant n°5 (index 4)
print(f"Q1 : {notes[4]}")
# 2. Afficher les 5 premiers étudiants
print(f"Q2 : {notes[:5]}")
# 3. Afficher les 10 derniers
print(f"Q3 : {notes[-10:]}")
# 4. Étudiants ayant la moyenne (note >= 10)
print(f"Q4 : {notes[notes >=10].size}")
# 5. Étudiants ayant 15 ou plus
print(f"Q5 : {notes[notes >= 15].size}")
# 6. Étudiants ayant entre 8 et 12 inclus
print(f"Q6 : {notes[(notes >= 8) & (notes <= 12)].size}")
# 7. Compter les étudiants en échec (< 10)
print(f"Q7 : {notes[notes < 10].size}")

Notes : [ 1 16 13  9  9 18  1 14  4  1 11 20 15 15 15 16 10  2 17  9 10  7  3 19
 16 13  8 17 11  9]
Q1 : 9
Q2 : [ 1 16 13  9  9]
Q3 : [10  7  3 19 16 13  8 17 11  9]
Q4 : 18
Q5 : 11
Q6 : 9
Q7 : 12


In [16]:
# difference entre len et size d'un array
mat = np.arange(16).reshape(4,4)
print(mat)
print(len(mat))
print(mat.size)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
4
16


## Operations et ufuncs

### Operations vectorisées

In [17]:
notes = np.array([12, 15, 8, 19, 14])
print(notes)
# operations arithmetiques
print(f"addition {notes + 1}")
print(f"multiplication {notes * 2}")
print(f"exposant {notes ** 2}")
print(f"division {notes /2}")

# operations entre array
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a / b)

[12 15  8 19 14]
addition [13 16  9 20 15]
multiplication [24 30 16 38 28]
exposant [144 225  64 361 196]
division [6.  7.5 4.  9.5 7. ]
[5 7 9]
[0.25 0.4  0.5 ]


### ufuncs : Universal Functions

In [18]:
a = np.arange(3)
print(a)
print(f"Exponentielle {np.exp(a)}")
print(f"Racine Carrée : {np.sqrt(a)}")
# print(f"Log : {np.log(a)}")

b = np.array([4,5,0])
print(f"b = {b}")
print(f"addition : {np.add(a, b)}")
print(f"maximum element par element : {np.maximum(a, b)}")
print(f"clip de l'addition : {np.clip(a+b, 0, 5)}")
print(f"clip normal : {np.clip(b, 2, 3)}")

[0 1 2]
Exponentielle [1.         2.71828183 7.3890561 ]
Racine Carrée : [0.         1.         1.41421356]
b = [4 5 0]
addition : [4 6 2]
maximum element par element : [4 5 2]
clip de l'addition : [4 5 2]
clip normal : [3 3 2]


## Le Broadcasting

In [19]:
notes = np.array([12, 15, 8, 19, 14])
print(notes + 1)

mat = np.ones((3,4))
print(mat)
print(mat.shape)
ligne = np.array([1,2,3,4])
print(ligne)
print(ligne.shape)
print(mat+ligne)

[13 16  9 20 15]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
[1 2 3 4]
(4,)
[[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]


### Exercice 3

In [20]:
rng = np.random.default_rng(42)
notes = rng.normal(12, 3, 20).round(1)  # 20 notes, moyenne 12, écart 3
print("Notes de la promo :", notes)

# N'oubliez pas après chaque question de plafonner les notes à 20
# 1. Calculer la moyenne générale de la classe
moyenne = sum(notes)/notes.size
moyenne = np.sum(notes) / notes.size
print(f"Q1 : {moyenne}")
# 2. Appliquer un bonus de 0.5 points à tous
print(f"Q2 : {np.clip(np.add(notes, 0.5), 0, 20)}")
bonus = np.clip(notes + 0.5, 0, 20)
print(f"Q2 : {bonus}")

# 3. Faites une majoration de 10%
bonus_avec_majoration = np.clip(bonus * 1.1, 0, 20)
print(f"Q3 : {bonus_avec_majoration}")
# 4. Calculer l'écart entre les notes originales et les notes apres les bonus
print(f"Q4 : {bonus_avec_majoration - notes}")

Notes de la promo : [12.9  8.9 14.3 14.8  6.1  8.1 12.4 11.1 11.9  9.4 14.6 14.3 12.2 15.4
 13.4  9.4 13.1  9.1 14.6 11.9]
Q1 : 11.895
Q2 : [13.4  9.4 14.8 15.3  6.6  8.6 12.9 11.6 12.4  9.9 15.1 14.8 12.7 15.9
 13.9  9.9 13.6  9.6 15.1 12.4]
Q2 : [13.4  9.4 14.8 15.3  6.6  8.6 12.9 11.6 12.4  9.9 15.1 14.8 12.7 15.9
 13.9  9.9 13.6  9.6 15.1 12.4]
Q3 : [14.74 10.34 16.28 16.83  7.26  9.46 14.19 12.76 13.64 10.89 16.61 16.28
 13.97 17.49 15.29 10.89 14.96 10.56 16.61 13.64]
Q4 : [1.84 1.44 1.98 2.03 1.16 1.36 1.79 1.66 1.74 1.49 2.01 1.98 1.77 2.09
 1.89 1.49 1.86 1.46 2.01 1.74]


## Statistiques et Aggrégations

In [21]:
notes = np.array([12, 15, 8, 19, 14, 10, 6, 17, 13, 9, 19])
print(notes)
print(f"somme : {np.sum(notes)}")
print(f"Moyenne : {np.mean(notes)}")
print(f"Mediane : {np.median(notes)}")
print(f"ecart-type : {np.std(notes)}")
print(f"max : {np.max(notes)}")

# Positions des extremes
print(f"indice du max : {np.argmax(notes)}")
print(f"indice du min : {np.argmin(notes)}")

# Centiles
print(f"25eme centile : {np.percentile(notes, 25)}")
print(f"90eme centile : {np.percentile(notes, 80)}")

[12 15  8 19 14 10  6 17 13  9 19]
somme : 142
Moyenne : 12.909090909090908
Mediane : 13.0
ecart-type : 4.187742838647644
max : 19
indice du max : 3
indice du min : 6
25eme centile : 9.5
90eme centile : 17.0


## Notion d'axes

In [22]:
# Matrice 3×4 = 3 étudiants, 4 matières
notes_eleves = np.array([
    [12, 15,  8, 19],   # étudiant 0
    [14, 10, 16,  7],   # étudiant 1
    [ 9, 13, 18, 11]    # étudiant 2
])
print(notes_eleves)

print(np.mean(notes_eleves, axis=0)) # vertical, par matiere
print(np.mean(notes_eleves, axis=1)) # horizontal, par eleve
# print(np.mean(notes_eleves))

[[12 15  8 19]
 [14 10 16  7]
 [ 9 13 18 11]]
[11.66666667 12.66666667 14.         12.33333333]
[13.5  11.75 12.75]


### Exercice 4

In [23]:
# Générer les données : 8 étudiants x 5 matières
rng = np.random.default_rng(60)
notes = rng.integers(0, 21, (8, 5))
matieres = ["Mathematiques", "Francais", "Physique", "Histoire-Geog.", "EPS"]

print("=== RELEVÉ DE NOTES ===")
print("Étudiant |", " ".join(f"{m:8s}" for m in matieres))
for i in range(8):
    print(f"  {i+1:3d}    |", " ".join(f"{n:9d}" for n in notes[i]))

# 1. Moyenne générale de toute la promo
moyenne_generale = np.mean(notes)
print(f"Q1 : Moyenne generale : {moyenne_generale}")
# 2. Écart-type général
print(f"Q2 : {np.std(notes)}")
# 3. Note minimale et maximale
print(f"Q3 : Notes Minimale = {min(min(x) for x in notes)}")
print(f"Q3 : Notes Maximale = {max(max(x) for x in notes)}")
print(np.min(notes), np.max(notes))
# 4. Moyenne par matière
print(f"Q4 : Moyenne par matière = {np.mean(notes, axis=0)}")
# 5. Moyenne par étudiant
print(f"Q5 : Moyenne par étudiant = {np.mean(notes, axis=1)}")
# 6. Étudiant avec la meilleure moyenne
moyenne = np.mean(notes, axis=1).argmax()
print(f"Q6 : {moyenne + 1}")
# 7. La matière la plus réussie
moyenne_matiere = np.mean(notes, axis=0)
indice = np.argmax(moyenne_matiere)
print(f"Q7 : meilleure matiere est {matieres[indice]} avec une moyenne de {moyenne_matiere[indice]}")
# 8. Combien d'étudiants ont une moyenne >= 10 ?
moyenne_etudiant = np.mean(notes, axis=1)
print(f"Q8 : {np.sum(moyenne_etudiant >= 10)}")
print(f"Q8 : {moyenne_etudiant[moyenne_etudiant >= 10].size}")
# 9. Top 3 des meilleures notes individuelles
top3 = np.sort(notes, axis=None)[-3:][::-1]
print(f"Q9 : {top3}")
top3 = np.sort(notes.flatten())[-3:][::-1]
print(f"Q9 : {top3}")
top3 = np.sort(notes.reshape(-1))[-3:][::-1]
print(f"Q9 : {top3}")
top3 = np.sort(notes.ravel())[-3:][::-1]
print(f"Q9 : {top3}")

print("\n--- Question 9:")
n_highest = 3
temp_notes = notes.copy()
noobs = []
etudiants = [1,2,3,4,5,6,7,8]
for n_note in range(n_highest):
    the_note = np.max(temp_notes)
    the_indices = np.argwhere(temp_notes == the_note)
    for r,c in the_indices:
        temp_notes[r, c] = -1
    noobs += [(the_note, etudiants[etudiant], matieres[matiere]) for etudiant, matiere in the_indices]

to_print  = f"Les {n_highest} meilleures notes sont obtenues de la manière suivante :\n     "
to_print += '\n     '.join(f"Note: {note} - Student {etudiant} in {matiere}" for note, etudiant, matiere in noobs)
print(to_print)

print("\n--- Question 9:")
n_highest = 3
temp_notes = notes.copy()
noobs = []

print(f"flatten {notes.flatten()}")
indices = np.partition(notes, -3, axis=None)
print(indices)  # Returns positions of partitioned elements
# print(notes.reshape(-1)[indices])

=== RELEVÉ DE NOTES ===
Étudiant | Mathematiques Francais Physique Histoire-Geog. EPS     
    1    |         3         6         8         0        20
    2    |         1        20        20        19        18
    3    |        20        11         4        20        18
    4    |        20         1         8        10         6
    5    |        19        14        12         0         8
    6    |        11         9        16         7        12
    7    |         2        12         6        11        15
    8    |         4        20         9        17         2
Q1 : Moyenne generale : 10.975
Q2 : 6.6614093854078655
Q3 : Notes Minimale = 0
Q3 : Notes Maximale = 20
0 20
Q4 : Moyenne par matière = [10.    11.625 10.375 10.5   12.375]
Q5 : Moyenne par étudiant = [ 7.4 15.6 14.6  9.  10.6 11.   9.2 10.4]
Q6 : 2
Q7 : meilleure matiere est EPS avec une moyenne de 12.375
Q8 : 5
Q8 : 5
Q9 : [20 20 20]
Q9 : [20 20 20]
Q9 : [20 20 20]
Q9 : [20 20 20]

--- Question 9:
Les 3 meilleures n

In [24]:
np.round(2.6578, 0)

np.float64(3.0)

In [25]:
np.argwhere(notes == 20)

array([[0, 4],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 3],
       [3, 0],
       [7, 1]])

### Exercice 5 BILAN

In [26]:
# On vous donne les notes de 25 eleves sur 4 évaluations (notées /20).

rng = np.random.default_rng(75)
eval1 = rng.normal(11, 4, 25).round(1).clip(0, 20)
eval2 = rng.normal(12, 3, 25).round(1).clip(0, 20)
eval3 = rng.normal(13, 5, 25).round(1).clip(0, 20)
eval4 = rng.normal(10, 4, 25).round(1).clip(0, 20)

print(eval1)
print(eval2)
print(eval3)
print(eval4)


# 1. Créer une matrice 25x4 à partir des 4 vecteurs d'évaluations
notes = np.column_stack([eval1, eval2, eval3, eval4])
notes = np.matrix_transpose([eval1, eval2, eval3, eval4])
notes = np.array([eval1, eval2, eval3, eval4]).T
notes = np.transpose([eval1, eval2, eval3, eval4])
notes = np.stack([eval1, eval2, eval3, eval4], axis=1)
notes = np.hstack((eval1.reshape(-1,1), eval2.reshape(-1,1), eval3.reshape(-1,1), eval4.reshape(-1,1)))
print(notes)

# 2. Afficher la forme de la matrice
print(notes.shape)
# 3. Calculer et afficher : Moyenne générale, Écart-type général, Note minimale et maximale
print(f"Q3 : moyenne {np.mean(notes):.2f}, ecart-type {np.std(notes):.2f}, min/max {np.min(notes)}/{np.max(notes)}")
# 4. Pour chaque évaluation, calculer : moyenne, médiane, min, max
print(f"Q4 : moyennes= {notes.mean(axis=0)}, médianes={np.median(notes, axis=0)}")
print(f"Q4 : min={np.min(notes, axis=0)}, max={np.max(notes, axis=0)}")
# 5. Calculer la moyenne de chaque eleve
moyenne_eleve = np.mean(notes, axis=1)
print(f"Q5 : moyenne eleve={moyenne_eleve}")
# 6. Combien ont une moyenne >= 10 ?
moyenne_dessus_10 = moyenne_eleve >= 10
print(f"Q6 : {sum(moyenne_dessus_10)}")
print(f"Q6 : {sum(moyenne_eleve >= 10)}")
# 7. Quels sont les indices des 3 meilleurs apprenants ?
print(f"Q7 : {np.argsort(moyenne_eleve)[-3:]}")
print(f"Q7 : {np.argpartition(moyenne_eleve,-3)[-3:]}")
# 8. Quels apprenants ont eu >= 15 à l'évaluation 3 ?
print(f"Q8 : {np.where(notes[:,2] >= 15, notes[:,2], None)}")
print(f"Q8 : {np.where(notes[:,2])}")
print(f"Q8 : {np.argwhere(notes[:,2] >= 15)}")
# 9. Créer un masque pour les apprenants ayant TOUTES les notes >= 8
masque = np.all(notes >= 8, axis=1)
print(f"Q9 : {masque}")
print(f"{np.where(masque)}")
# 10. Bonus de 2 points sur les notes inférieures a 8 uniquement
notes[notes < 8] += 2
# notes = np.where(notes >= 8, notes, notes+2)
# notes = np.where(notes < 8, notes+2, notes)
print(f"Q10 : {notes}")
# 11. Bonus de 5 points sur l'évaluation 1 (plafonné à 20)
# notes[:,0] = np.clip((notes[:,0] + 5), 0, 20)
notes[:,0] += 5
# notes[:,0] = np.clip(notes[:,0], None, 20)
# notes[:,0] = np.clip(notes[:,0], max=20)
notes[:,0] = np.minimum(notes[:,0],20)

print(f"Q11 : {notes}")
# 12. Appliquer la normalisation Min-Max sur les notes de l'évaluation 1
#v1
notes_min = notes[:,0].min()
notes_max = notes[:,0].max()
eval1_norm = []
for une_note in notes[:,0]:
    eval1_norm.append((une_note - notes_min) / (notes_max - notes_min))
eval1_norm = np.array(eval1_norm)

#v2
notes_min = notes[:,0].min()
notes_max = notes[:,0].max()
eval1_norm = ((notes[:,0] - notes_min) / (notes_max - notes_min))

#v3
eval1_norm = ((notes[:,0] - notes[:,0].min()) / (notes[:,0].max() - notes[:,0].min()))

print(f"Q12 : {eval1_norm}")

# 13. Standardiser les notes de l'évaluation 2
eval2_standardized = (notes[:,1]-np.mean(notes[:,1])) / np.std(notes[:,1])
print(f"Q13 : {eval2_standardized}")
print(f"Q13 : mean={eval2_standardized.mean():.10f}   std={eval2_standardized.std()}")
# 14. Afficher un array de la meilleure note dans chaque matiere entre les 10 meilleurs eleves de la classe
print(f"Q14 : les moyennes : {notes.mean(axis=1)}")
print(f"Q14 : moyennes croissantes : {np.sort(notes.mean(axis=1))}")
top10_idx = np.argsort(notes.mean(axis=1))[-10:]
top10_notes = notes[top10_idx]
meilleures_notes = top10_notes.max(axis=0)
print(f"Q14 : {meilleures_notes}")

top10_idx = np.argpartition(notes.mean(axis=1), -10)[-10:]
top10_notes = notes[top10_idx]
meilleures_notes = top10_notes.max(axis=0)
print(f"Q14 : {meilleures_notes}")

meilleures_notes = notes[np.argpartition(notes.mean(axis=1), -10)[-10:]].max(axis=0)
print(f"Q14 : {meilleures_notes}")

[ 6.6 12.6 12.6 12.7 13.  11.1 12.8 15.3 18.4 10.4  7.7  5.4 12.1 10.3
 17.4  5.8  8.9  7.4 11.8 10.2  7.6  8.6 15.  16.  13.4]
[14.  13.9 10.3 12.   9.1 14.  10.3 10.4 13.1 13.1 11.   8.8  9.8 10.1
 12.5 13.9 11.1 13.5  5.8 11.9 11.3  6.6 14.9 12.3 17.1]
[16.3 11.9  1.2  7.4 17.2 20.  14.5  8.5 16.4 11.3  6.4 16.8  7.4 11.4
  8.1 17.4 11.7 11.3 13.1 17.8  9.6 17.6  8.7 18.3  8.1]
[ 7.4 16.2 13.7 11.  10.  18.4  9.8  9.5  6.   7.   7.8  5.8 14.1 11.9
  9.1  8.5 16.2  8.5 16.1  7.5  9.  15.1  9.6 13.7  8.8]
[[ 6.6 14.  16.3  7.4]
 [12.6 13.9 11.9 16.2]
 [12.6 10.3  1.2 13.7]
 [12.7 12.   7.4 11. ]
 [13.   9.1 17.2 10. ]
 [11.1 14.  20.  18.4]
 [12.8 10.3 14.5  9.8]
 [15.3 10.4  8.5  9.5]
 [18.4 13.1 16.4  6. ]
 [10.4 13.1 11.3  7. ]
 [ 7.7 11.   6.4  7.8]
 [ 5.4  8.8 16.8  5.8]
 [12.1  9.8  7.4 14.1]
 [10.3 10.1 11.4 11.9]
 [17.4 12.5  8.1  9.1]
 [ 5.8 13.9 17.4  8.5]
 [ 8.9 11.1 11.7 16.2]
 [ 7.4 13.5 11.3  8.5]
 [11.8  5.8 13.1 16.1]
 [10.2 11.9 17.8  7.5]
 [ 7.6 11.3  9.6  9. ]
 [ 8.

# Pandas

In [27]:
# pip install pandas
# pour notebook : !pip install pandas

import pandas as pd

print(pd.__version__)

3.0.3


## Series Pandas

In [28]:
data = [100, 102, 104]
data = [True, False, True]
data = [[1], [2], [3]]
data = ["aqqq", "qqqb", "cqqq"]
# data = [(1,2), (3,2), (1,4)]
# data = [100, False, "gshsrgswhwdtfy<<"]
series = pd.Series(data)
print(series)

0    aqqq
1    qqqb
2    cqqq
dtype: str


In [29]:
data = [100, 102, 104]

ma_series = pd.Series(data, index=["a", "b", "c"])
print(ma_series)

a    100
b    102
c    104
dtype: int64


### Acceder a une valeur dans la série

In [30]:
# localisation par label
print(ma_series["a"])
print(ma_series.loc["a"])
ma_series.loc["c"] = 200
print(ma_series)

# localisation par position
print(ma_series.iloc[2])

100
100
a    100
b    102
c    200
dtype: int64
200


### Filtrer par valeur

In [31]:
# print(ma_series)
print(ma_series[ma_series >= 200])

c    200
dtype: int64


In [32]:
ma_series >= 200

a    False
b    False
c     True
dtype: bool

In [33]:
calories = {
    "Jour 1": 1750,
    "Jour 2": 2100,
    "Jour 3": 1700
}

ma_series = pd.Series(calories)
print(ma_series)

ma_series["Jour 3"] += 500
print(ma_series[ma_series < 2000])

Jour 1    1750
Jour 2    2100
Jour 3    1700
dtype: int64
Jour 1    1750
dtype: int64


In [34]:
s = pd.Series([10, None, "30"])
print(s.isna())
# Dans le cas ou la liste est de type objet, None est gardé en None, ne devient par NaN

0    False
1     True
2    False
dtype: bool


In [35]:
if isinstance(1, (int, str, list, float)):
    print("oui")
if isinstance(1, (str, list, float, bool)):
    print("non")

oui


## Pandas DataFrame

In [36]:
# a partir d'un dictionnaire
d = {
    "nom":    ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "age":    [22, 25, 21, 23, 24],
    "note":   [15, 12, 8, 19, 14],
    "ville":  ["Roanne", "St-Étienne", "Roanne", "Lyon", "Villeurbanne"]
}

df = pd.DataFrame(d)
print(df)

       nom  age  note         ville
0    Alice   22    15        Roanne
1      Bob   25    12    St-Étienne
2  Charlie   21     8        Roanne
3    Diana   23    19          Lyon
4      Eve   24    14  Villeurbanne


In [37]:
# liste de dictionnaires
data2 = [
    {"nom": "Alice", "note": 15},
    {"nom": "Bob", "note": 12},
    {"nom": "Charlie"}, 
]
df2 = pd.DataFrame(data2)
print(df2)

       nom  note
0    Alice  15.0
1      Bob  12.0
2  Charlie   NaN


In [38]:
rng = np.random.default_rng(42)
notes = rng.integers(0, 21, (5, 3))

df3 = pd.DataFrame(
    notes,
    columns=["Python", "SQL", "Stats"],
    index=["Élève A", "Élève B", "Élève C", "Élève D", "Élève E"]
)
print(df3)

         Python  SQL  Stats
Élève A       1   16     13
Élève B       9    9     18
Élève C       1   14      4
Élève D       1   11     20
Élève E      15   15     15


In [39]:
# Depuis un fichier CSV
# df = pd.read_csv("emplacement/du/fichier/fichier.csv")

In [40]:
# df = pd.read_csv(
#     "emplacement/du/fichier/fichier.csv", #emplacement de mon fichier
#     names=["nom1", "nom2"],               #les nouveaux noms des colonnes
#     nrows=100,                            # nombre de lignes a lire
#     )

In [41]:
import os

# os.getcwd()

### Exercice 1

In [42]:
etudiants = {
    "prenom": ["Lucas", "Emma", "Hugo", "Léa", "Tom"],
    "age":    [23, 28, 19, 32, 26],
    "ville":   ["Roanne", "Saint-Étienne", "Roanne", "Lyon", "Saint-Étienne"],
    "niveau d'études": ["Licence", "Master", "Licence", "Master", "Master"]
}

# 1. Depuis le dictionnaire créez un DataFrame
df = pd.DataFrame(etudiants)
print(df)
# 2. Créez un array de 10 lignes x 3 colonnes de notes aléatoires entre 0 et 20 (utilisez seed=123) 
# Nommez les colonnes "matiere1", "matiere2", "matiere3", mettez-les dans un nouveau DataFrame
rng = np.random.default_rng(123)
notes = rng.integers(0,21,(10,3))
df2 = pd.DataFrame(notes, columns=["matiere1", "matiere2", "matiere3"])
print(df2)
# 3. Afficher la forme des deux DataFrames
print(f"Q3 : Forme dataframe etudiant : {df.shape}\nQ3 : Forme dataframe notes : {df2.shape}")
# 4. Trouver trois facons de joindre ces deux DataFrames, et sauvegarder le resultat dans un nouveau DataFrame
#CONCAT
df_concatenante = pd.concat([df, df2], axis=1)
print(f"Q4 CONCAT : \n{df_concatenante}")
#JOIN
df_join = df.join(df2)
print(f"Q4 JOIN : \n{df_join}")
#MERGE
df_merged = pd.merge(df2, df, left_index=True, right_index=True)
print(f"Q4 MERGE : \n{df_merged}")
#COMBINE FIRST
df_combine_first = df.combine_first(df2)
print(f"Q4 COMBINE FIRST : \n{df_combine_first}")
# 5. Créer un 4e DataFrame en ne gardant que les colonnes prenom et matiere1
df3 = df_merged[["prenom", "matiere1"]]
print(f"Q5 : {df3}")
df4 = df_merged.loc[:, ["prenom", "matiere1"]]
print(f"Q5 : {df4}")
df5 = df_merged.filter(items=["prenom", "matiere1"])
print(f"Q5 : {df5}")

  prenom  age          ville niveau d'études
0  Lucas   23         Roanne         Licence
1   Emma   28  Saint-Étienne          Master
2   Hugo   19         Roanne         Licence
3    Léa   32           Lyon          Master
4    Tom   26  Saint-Étienne          Master
   matiere1  matiere2  matiere3
0         0        14        12
1         1        19         4
2         5         3         7
3         3         7        17
4         9        19         9
5         5        16        17
6        18        18         0
7        10         5         5
8         5        17        16
9         4         8        15
Q3 : Forme dataframe etudiant : (5, 4)
Q3 : Forme dataframe notes : (10, 3)
Q4 CONCAT : 
  prenom   age          ville niveau d'études  matiere1  matiere2  matiere3
0  Lucas  23.0         Roanne         Licence         0        14        12
1   Emma  28.0  Saint-Étienne          Master         1        19         4
2   Hugo  19.0         Roanne         Licence         5      

### Exploration Generale d'un DataFrame

In [43]:
etudiants = {
    "prenom": ["Lucas", "Emma", "Hugo", "Léa", "Tom"],
    "age":    [23, 28, 19, 32, 26],
    "ville":   ["Roanne", "Saint-Étienne", "Roanne", "Lyon", "Saint-Étienne"],
    "niveau d'études": ["Licence", "Master", "Licence", "Master", "Master"]
}
df = pd.DataFrame(etudiants)

In [44]:
df.head() # 5 premieres lignes
df.tail() # 3 dernieres lignes
# df.sample(3) # 3 lignes au hasard

,prenom,age,ville,niveau d'études
0,Lucas,23,Roanne,Licence
1,Emma,28,Saint-Étienne,Master
2,Hugo,19,Roanne,Licence
3,Léa,32,Lyon,Master
4,Tom,26,Saint-Étienne,Master


In [45]:
df.describe()

,age
count,5.000000
mean,25.600000
std,4.929503
min,19.000000
25%,23.000000
50%,26.000000
75%,28.000000
max,32.000000


In [46]:
df.describe(include="all")

,prenom,age,ville,niveau d'études
count,5,5.000000,5,5
unique,5,NaN,3,2
top,Lucas,NaN,Roanne,Master
freq,1,NaN,2,3
mean,NaN,25.600000,NaN,NaN
std,NaN,4.929503,NaN,NaN
min,NaN,19.000000,NaN,NaN
25%,NaN,23.000000,NaN,NaN
50%,NaN,26.000000,NaN,NaN
75%,NaN,28.000000,NaN,NaN


In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   prenom           5 non-null      str  
 1   age              5 non-null      int64
 2   ville            5 non-null      str  
 3   niveau d'études  5 non-null      str  
dtypes: int64(1), str(3)
memory usage: 292.0 bytes


In [48]:
df["ville"].value_counts()

ville
Roanne           2
Saint-Étienne    2
Lyon             1
Name: count, dtype: int64

In [49]:
df["niveau d'études"].unique()

<StringArray>
['Licence', 'Master']
Length: 2, dtype: str

In [50]:
df.nunique()

prenom             5
age                5
ville              3
niveau d'études    2
dtype: int64

### exercice 2

In [51]:
# Charger les données
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

# 1. Dimensions du dataframe
print(f"Q1 : {df.shape}")
# 2. Liste des colonnes
print(f"Q2 : {df.columns}")
print(f"Q2 : {list(df.columns)}")
print(f"Q2 : {list(df)}")
# 3. Types des colonnes
print(f"Q3 : {df.dtypes}")
# 4. print des 5 premières lignes
print(f"Q4 : \n{df.head()}")
print(f"Q4 : \n{df.iloc[:5]}")
# 5. Faire un résumé statistique
print(f"Q5 : \n{df.describe(include="all").round(2)}")
# 6. Combien a-t-on de valeurs uniques par colonne ?
print(f"Q6 : {df.nunique(dropna=False)}")
print(f"Q6 : {df.nunique()}")
# 7. Y a-t-il des valeurs manquantes ? Si oui combien au total ?
print(f"Q7 : \n{df.isnull().sum().sum()}")
# 8. Quel jour y a-t-il le plus de clients ?
print(f"Q8 : {df["day"].value_counts().iloc[0]}")
print(f"Q8 : {df["day"].mode()[0]}")
print(f"{df.groupby(df["day"]).size().idxmax()}")
# Q8 affichage en pourcentages
print(f"Q8 bonus : \n{df["day"].value_counts(normalize=True).iloc[0]*100}")
print(f"Q8 Bonus : \n{df["day"].value_counts()*100/len(df)}")
# Q8 Bonus 2 le plus de clients mais en prenant en compte la colonne size
print(f"Q8 bonus 2 : \n{(df.groupby("day")["size"].sum()/df["size"].sum()*100).round(2)}")
print(f"Q8 bonus 2 : {df.groupby("day")["size"].sum().nlargest(1)}")
# df.groupby("day")["size"].value_counts()
clients_par_jour = df.groupby("day")["size"].sum()
jour_max = clients_par_jour.idxmax()
nb_clients = clients_par_jour.max()
print(f"Q8 Bonus 2 : {nb_clients}: {jour_max}")
x,y = df.groupby("day")["size"].sum().nlargest(1).reset_index().squeeze()
print(x,y)

Q1 : (244, 7)
Q2 : Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')
Q2 : ['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']
Q2 : ['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']
Q3 : total_bill    float64
tip           float64
sex               str
smoker            str
day               str
time              str
size            int64
dtype: object
Q4 : 
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
Q4 : 
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun 

### Selection et filtrage

In [52]:
etudiants = {
    "prenom": ["Lucas", "Emma", "Hugo", "Léa", "Tom"],
    "age":    [23, 28, 19, 32, 26],
    "ville":   ["Roanne", "Saint-Etienne", "Roanne", "Lyon", "Saint-Etienne"],
    "niveau d'études": ["Licence", "Master", "Licence", "Master", "Master"]
}
df = pd.DataFrame(etudiants)
df

,prenom,age,ville,niveau d'études
0,Lucas,23,Roanne,Licence
1,Emma,28,Saint-Etienne,Master
2,Hugo,19,Roanne,Licence
3,Léa,32,Lyon,Master
4,Tom,26,Saint-Etienne,Master


In [53]:
print(df["prenom"])
print(type(df["prenom"]))

print(df[["prenom","ville"]])
print(type(df[["prenom","ville"]]))

df["ville_prenom"] = df["ville"] + df["prenom"]
print(df)

print(type(df["ville"]))
print(type(df[["ville"]]))

0    Lucas
1     Emma
2     Hugo
3      Léa
4      Tom
Name: prenom, dtype: str
<class 'pandas.Series'>
  prenom          ville
0  Lucas         Roanne
1   Emma  Saint-Etienne
2   Hugo         Roanne
3    Léa           Lyon
4    Tom  Saint-Etienne
<class 'pandas.DataFrame'>
  prenom  age          ville niveau d'études       ville_prenom
0  Lucas   23         Roanne         Licence        RoanneLucas
1   Emma   28  Saint-Etienne          Master  Saint-EtienneEmma
2   Hugo   19         Roanne         Licence         RoanneHugo
3    Léa   32           Lyon          Master            LyonLéa
4    Tom   26  Saint-Etienne          Master   Saint-EtienneTom
<class 'pandas.Series'>
<class 'pandas.DataFrame'>


In [54]:
# .loc[lignes, colonnes]

print(df.loc[:,"prenom"])
print(df.loc[:3, ["ville", "prenom"]])
print(df.loc[2])
print(df.loc[df["age"] < 23])

0    Lucas
1     Emma
2     Hugo
3      Léa
4      Tom
Name: prenom, dtype: str
           ville prenom
0         Roanne  Lucas
1  Saint-Etienne   Emma
2         Roanne   Hugo
3           Lyon    Léa
prenom                   Hugo
age                        19
ville                  Roanne
niveau d'études       Licence
ville_prenom       RoanneHugo
Name: 2, dtype: object
  prenom  age   ville niveau d'études ville_prenom
2   Hugo   19  Roanne         Licence   RoanneHugo


In [55]:
#.iloc[lignes, colonnes] : basé sur la position

df.iloc[:, -2:]

df.iloc[[True, False, True] + [False]*2]

,prenom,age,ville,niveau d'études,ville_prenom
0,Lucas,23,Roanne,Licence,RoanneLucas
2,Hugo,19,Roanne,Licence,RoanneHugo


#### Exercice 3

In [56]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
print(df)
# 1. Sélectionner la colonne 'tip' comme une Series
print(f"Q1 : \n{df["tip"]}")
print(f"Q1 : \n{df.loc[:, "tip"]}")
# 2. Sélectionner les colonnes 'total_bill' et 'day' comme un DataFrame
print(f"Q2 : \n{df[["total_bill", "day"]]}")
print(f"Q2 : \n{df.loc[:, ["total_bill", "day"]]}")
# 3. Afficher les 5 premières lignes avec .loc
print(f"Q3 : \n{df.loc[:4]}")
print(f"Q3 : \n{df[:5]}")
# 4. Afficher les lignes 10 à 15 (incluses), avec les colonnes 'tip' et 'sex'
print(f"Q4 : \n{df.loc[10:15][["tip", "sex"]]}")
print(f"Q4 : \n{df.loc[10:15, ["tip", "sex"]]}")
# 5. Afficher la 3e ligne avec .iloc
print(f"Q5 : \n{df.iloc[2]}")
# 6. Filtrer les repas avec total_bill > 30
print(f"Q6 : \n{df[df["total_bill"] > 30]}")
# 7. Filtrer les repas du dimanche (Sun) avec un tip > 5
print(f"Q7 : \n{df[(df["day"] == "Sun") & (df["tip"] > 5)]}")
# 8. Filtrer les repas du soir (Dinner) avec plus de 3 personnes
print(f"Q8 : \n{df.loc[(df["time"] == "Dinner") & (df["size"] > 3)]}")
print(f"Q8 : \n{df[(df["time"] == "Dinner") & (df["size"] > 3)]}")
# 9. Quelle est la moyenne du tip pour les repas de plus de 40€ ?
print(f"Q9 : \n{df[df["total_bill"] > 40]["tip"].mean()}")
# 10. Combien de femmes ont laissé un tip supérieur à 5€ ?
print(f"Q10 : {((df["sex"] == "Female") & (df["tip"] > 5)).sum()}")
print(len(df[(df["sex"] == "Female") & (df["tip"] > 5)]))
print(len(df.loc[(df["sex"] == "Female") & (df["tip"] > 5), ["sex"]]))

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]
Q1 : 
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64
Q1 : 
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
2

## Nettoyage et transformation

In [57]:
etudiants = {
    "prenom": ["Lucas", "Emma", "Hugo", "Léa", "Tom"],
    "age":    [23, np.nan, 19, 32.0, np.nan],
    "ville":   ["Roanne", "Saint-Etienne", "Roanne", None, "Saint-Etienne"],
    "niveau": ["Licence", None, "Licence", "Master", "Master"]
}
df = pd.DataFrame(etudiants)
df

,prenom,age,ville,niveau
0,Lucas,23.0,Roanne,Licence
1,Emma,NaN,Saint-Etienne,NaN
2,Hugo,19.0,Roanne,Licence
3,Léa,32.0,NaN,Master
4,Tom,NaN,Saint-Etienne,Master


In [58]:
print(df.isna()) #masque booléen
print(df.isna().sum()) #nombre de valeurs manquantes par colonne
print(df.isna().sum().sum()) #nombre total de valeur manquantes

   prenom    age  ville  niveau
0   False  False  False   False
1   False   True  False    True
2   False  False  False   False
3   False  False   True   False
4   False   True  False   False
prenom    0
age       2
ville     1
niveau    1
dtype: int64
4


In [59]:
# Supprimer les lignes qui ont au moins un NaN
df.dropna()
# supprimer les lignes où une colonne spécifique a des NaN
df.dropna(subset=["age"])
# Supprimer les colonnes avec des NaN
df.dropna(axis=1)

,prenom
0,Lucas
1,Emma
2,Hugo
3,Léa
4,Tom


In [60]:
# Remplacer par une valeur fixe
print(df["age"].fillna(0))

# Remplacer par la moyenne
print(df["age"].fillna(df["age"].mean()))

# Forward fill / backward fill
df.ffill() #propage la valeur du haut vers le bas (si la première valeur est manquante, elle reste manquante)
df.bfill() # propage la valeur du bas vers le haut
df.fillna({
    "age": df["age"].median(),
    "ville": "Inconnu",
    "niveau": "Inconnu"
})

0    23.0
1     0.0
2    19.0
3    32.0
4     0.0
Name: age, dtype: float64
0    23.000000
1    24.666667
2    19.000000
3    32.000000
4    24.666667
Name: age, dtype: float64


,prenom,age,ville,niveau
0,Lucas,23.0,Roanne,Licence
1,Emma,23.0,Saint-Etienne,Inconnu
2,Hugo,19.0,Roanne,Licence
3,Léa,32.0,Inconnu,Master
4,Tom,23.0,Saint-Etienne,Master


In [61]:
df["age"] = df["age"].fillna(df["age"].mean())

In [62]:
df

,prenom,age,ville,niveau
0,Lucas,23.000000,Roanne,Licence
1,Emma,24.666667,Saint-Etienne,NaN
2,Hugo,19.000000,Roanne,Licence
3,Léa,32.000000,NaN,Master
4,Tom,24.666667,Saint-Etienne,Master


In [63]:
df["age"] = df["age"].astype(int)
df

,prenom,age,ville,niveau
0,Lucas,23,Roanne,Licence
1,Emma,24,Saint-Etienne,NaN
2,Hugo,19,Roanne,Licence
3,Léa,32,NaN,Master
4,Tom,24,Saint-Etienne,Master


### Exercice 4

In [64]:
data = {
    "eleve": ["Léa", "Hugo", "Sarah", "Maxime", "Inès", "Paul"],
    "python":    ["18", 14, np.nan, 11, 16, 9],
    "sql":       [15, np.nan, 17, 8, np.nan, 12],
    "stats":     [12, 16.0, 14, 10, 15, np.nan],
    "present":   [True, True, True, True, True, False]
}
df = pd.DataFrame(data)
# 1. Faites en sorte que la matière "python" soit de type entier ou flotant
print(df.dtypes)
df["python"] = df["python"].astype(float)
df["python"] = pd.to_numeric(df["python"], errors="coerce")
print(f"Q1 : {df.dtypes}")
print(f"Q1 : {df}")

# 2. Diagnostiquer les valeurs manquantes
print(f"Q2 : \n{df.isna().sum()}")
# 3. Remplir les notes manquantes avec la moyenne de leur matière
# 1e maniere
df.fillna({
    "python": df["python"].mean(),
    "sql": df["sql"].mean(),
    "stats": df["stats"].mean()
    }, inplace=True)
# 2e maniere
df.fillna(df.mean(numeric_only=True), inplace=True)
#3e maniere
df["python"] = df["python"].fillna(df["python"].mean().round(2))
df["sql"] = df["sql"].fillna(df["sql"].mean().round(2))
df["stats"] = df["stats"].fillna(df["stats"].mean().round(2))
print(f"Q3 : \n{df}")
# 4. Créer une colonne "moyenne" (moyenne des 3 matières)
df["moyenne"] = df[["python", "sql", "stats"]].mean(axis=1, skipna=True).round(1)
print(f"Q4 : \n{df}")
# 5. Créer une colonne "statut" : "Validé" si moyenne >= 10, "Rattrapage" si entre 8 et 10, "Échec" sinon
#1e maniere
def statut_moyenne(moyenne):
    if moyenne >= 10:
        return "Validé"
    elif moyenne >= 8:
        return "Rattrapage"
    else:
        return "Echec"
df["statut"] = df["moyenne"].apply(statut_moyenne)
print(f"Q5 : \n{df}")
#2e maniere
borne = [float("-inf"), 8, 10, float("inf")]
label = ["Echec", "Rattrapage", "Validé"]
df["statut"] = pd.cut(df["moyenne"], bins=borne, labels=label, right=False)
print(f"Q5 : \n{df}")
#3e maniere
conditions = [(df["moyenne"] >= 10), (df["moyenne"]>= 8)]
value = ["Validé", "Rattrapage"]
df["statut"] = np.select(conditions, value, default="Echec")
df["statut"] = np.where(df["moyenne"] >= 10, "Validé", np.where(df["moyenne"] >= 8, "Rattrapage", "Echec"))
print(f"Q5 : \n{df}")
# 4e maniere
def statut_moyenne(moyenne):
    if moyenne >= 10:
        return "Validé"
    elif moyenne >= 8:
        return "Rattrapage"
    else:
        return "Echec"
df["statut"] = df["moyenne"].map(statut_moyenne)
print(f"Q5 : \n{df}")
#5e maniere
df.loc[df["moyenne"] >= 10, "statut"] = "Validé"
df.loc[df["moyenne"] < 8, "statut"] = "Echec"
df.loc[(df["moyenne"] >= 8) & (df["moyenne"] < 10), "statut"] = "Rattrapage"
print(f"Q5 : \n{df}")

# 6. Supprimer la colonne "present"
df.drop(["present"], axis=1, inplace=True)
print(f"Q6 : \n{df}")
# 7. Compter combien d'eleves sont "Validé"
print(f"Q7 : {(df["statut"] == "Validé").sum()}")
# 8. Quelle est la moyenne générale de la promo ?
print(f"Q8 : {df["moyenne"].mean()}")

eleve          str
python      object
sql        float64
stats      float64
present       bool
dtype: object
Q1 : eleve          str
python     float64
sql        float64
stats      float64
present       bool
dtype: object
Q1 :     eleve  python   sql  stats  present
0     Léa    18.0  15.0   12.0     True
1    Hugo    14.0   NaN   16.0     True
2   Sarah     NaN  17.0   14.0     True
3  Maxime    11.0   8.0   10.0     True
4    Inès    16.0   NaN   15.0     True
5    Paul     9.0  12.0    NaN    False
Q2 : 
eleve      0
python     1
sql        2
stats      1
present    0
dtype: int64
Q3 : 
    eleve  python   sql  stats  present
0     Léa    18.0  15.0   12.0     True
1    Hugo    14.0  13.0   16.0     True
2   Sarah    13.6  17.0   14.0     True
3  Maxime    11.0   8.0   10.0     True
4    Inès    16.0  13.0   15.0     True
5    Paul     9.0  12.0   13.4    False
Q4 : 
    eleve  python   sql  stats  present  moyenne
0     Léa    18.0  15.0   12.0     True     15.0
1    Hugo    14.0 

## Groupby et agrégation

In [65]:
etudiants = {
    "prenom": ["Lucas", "Emma", "Hugo", "Léa", "Tom"],
    "age":    [23, 28, 19, 32, 26],
    "ville":   ["Roanne", "Saint-Etienne", "Roanne", "Lyon", "Saint-Etienne"],
    "niveau d'études": ["Licence", "Master", "Licence", "Master", "Master"],
    "moyenne générale": [15.2, 11.9, 8.9, 16.5, 11.1]
}
df = pd.DataFrame(etudiants)
df

,prenom,age,ville,niveau d'études,moyenne générale
0,Lucas,23,Roanne,Licence,15.2
1,Emma,28,Saint-Etienne,Master,11.9
2,Hugo,19,Roanne,Licence,8.9
3,Léa,32,Lyon,Master,16.5
4,Tom,26,Saint-Etienne,Master,11.1


In [66]:
df.agg(["min","max"])

,prenom,age,ville,niveau d'études,moyenne générale
min,Emma,19,Lyon,Licence,8.9
max,Tom,32,Saint-Etienne,Master,16.5


In [67]:
df.agg({
    "moyenne générale": ["sum", "mean", "median"],
    "age": "max"
})

,moyenne générale,age
sum,63.60,NaN
mean,12.72,NaN
median,11.90,NaN
max,NaN,32.0


In [68]:
for nom, groupe in df.groupby("niveau d'études"):
    print(nom)
    print(groupe)

Licence
  prenom  age   ville niveau d'études  moyenne générale
0  Lucas   23  Roanne         Licence              15.2
2   Hugo   19  Roanne         Licence               8.9
Master
  prenom  age          ville niveau d'études  moyenne générale
1   Emma   28  Saint-Etienne          Master              11.9
3    Léa   32           Lyon          Master              16.5
4    Tom   26  Saint-Etienne          Master              11.1


In [69]:
for nom, groupe in df.groupby(["niveau d'études", "ville"]):
    print(nom)
    print(groupe)

('Licence', 'Roanne')
  prenom  age   ville niveau d'études  moyenne générale
0  Lucas   23  Roanne         Licence              15.2
2   Hugo   19  Roanne         Licence               8.9
('Master', 'Lyon')
  prenom  age ville niveau d'études  moyenne générale
3    Léa   32  Lyon          Master              16.5
('Master', 'Saint-Etienne')
  prenom  age          ville niveau d'études  moyenne générale
1   Emma   28  Saint-Etienne          Master              11.9
4    Tom   26  Saint-Etienne          Master              11.1


In [70]:
df.groupby("niveau d'études")[["age", "moyenne générale"]].agg(["min", "max", "std"]).round(2)

age           moyenne générale            
                min max   std              min   max   std
niveau d'études                                           
Licence          19  23  2.83              8.9  15.2  4.45
Master           26  32  3.06             11.1  16.5  2.91

In [71]:
def mon_modulo_de_2(x):
    return np.sum(x % 2)
df.groupby("niveau d'études")[["age", "moyenne générale"]].agg(["min", "max", "std", mon_modulo_de_2]).round(2)

age                           moyenne générale              \
                min max   std mon_modulo_de_2              min   max   std   
niveau d'études                                                              
Licence          19  23  2.83               2              8.9  15.2  4.45   
Master           26  32  3.06               0             11.1  16.5  2.91   

                                 
                mon_modulo_de_2  
niveau d'études                  
Licence                     2.1  
Master                      3.5

In [72]:
df.groupby("ville").get_group("Saint-Etienne")

,prenom,age,ville,niveau d'études,moyenne générale
1,Emma,28,Saint-Etienne,Master,11.9
4,Tom,26,Saint-Etienne,Master,11.1


In [73]:
df["ville"].value_counts()

ville
Roanne           2
Saint-Etienne    2
Lyon             1
Name: count, dtype: int64

In [74]:
df["ville"].value_counts(normalize=True)

ville
Roanne           0.4
Saint-Etienne    0.4
Lyon             0.2
Name: proportion, dtype: float64

### Exercice 5

In [ ]:
# Création du dataset
rng = np.random.default_rng(101)
sites = ["Roanne"] * 10 + ["St-Étienne"] * 10 + ["Lyon"] * 10
niveaux = rng.choice(["Débutant", "Intermédiaire", "Avancé"], 30, p=[0.5, 0.3, 0.2])
note = rng.normal(14, 4, 30).round(1).clip(0, 20)
heures_etude = rng.integers(5, 30, 30)
abandon = rng.choice([0, 1], 30, p=[0.8, 0.2])
df = pd.DataFrame({
    "site": sites,
    "niveau": niveaux,
    "note": note,
    "heures_etude": heures_etude,
    "abandon": abandon
})
print(df)
# 1. Note moyenne par site
print(f"Q1 : \n{df.groupby("site")["note"].mean()}")
# 2. Statistiques par site ("mean", "std", "min", "max", "count")
print(f"Q2 : \n{df.groupby("site")["note"].agg(["mean", "std", "min", "max", "count"]).round(2)}")
# 3. Note moyenne par site ET par niveau
print(f"Q3 : \n{df.groupby(["site", "niveau"])["note"].agg(["mean"])}")
print(f"Q3 : \n{df.groupby(["site", "niveau"])["note"].mean()}")
print(f"Q3 : \n{df.groupby(["site", "niveau"]).agg(note_moyenne=pd.NamedAgg("note", "mean"))}")
# 4. Nombre d'apprenants par site
print(f"Q4 : \n{df.groupby(["site"])["niveau"].agg(["count"])}")
print(f"Q4 : \n{df["site"].value_counts()}")
print(f"Q4 : \n{df.groupby("site").size()}")
print(f"Q4 : \n{df.groupby("site")["site"].count()}")
# df["apprenant"] = 1
# print(f"Q4 : \n{df.groupby("site")["apprenant"].sum()}")
nombre_apprenants_par_site = df.groupby("site").size().reset_index(name="nombre_apprenants")
print(f"Q4 : \n{nombre_apprenants_par_site}")
# 5. Taux d'abandon par site
print(f"Q5 : \n{df.groupby("site")[["abandon"]].mean()*100}")
# 6. Heures d'étude moyennes par niveau
print(f"Q6 : \n{df.groupby("niveau")["heures_etude"].mean().round(2)}")
# 7. Classement des sites avec la meilleure note moyenne
print(f"Q7 : {df.groupby("site")["note"].mean().sort_values(ascending=False)}")

          site         niveau  note  heures_etude  abandon
0       Roanne         Avancé   7.4             8        1
1       Roanne       Débutant   8.3            21        1
2       Roanne  Intermédiaire   9.6             6        1
3       Roanne  Intermédiaire  15.2             5        0
4       Roanne       Débutant  10.9            13        1
5       Roanne         Avancé  19.2             6        0
6       Roanne         Avancé  15.0            10        0
7       Roanne       Débutant  15.5             8        0
8       Roanne         Avancé  17.0            27        0
9       Roanne       Débutant  15.4            27        1
10  St-Étienne         Avancé   8.4             9        0
11  St-Étienne  Intermédiaire  20.0            24        0
12  St-Étienne       Débutant  19.9             7        0
13  St-Étienne       Débutant  20.0            21        0
14  St-Étienne         Avancé  11.0            28        0
15  St-Étienne  Intermédiaire   6.6            21       

## Exercice nettoyage dataset pokemon